version: '3'

services:
  strapi:
    container_name: strapi
    image: strapi/strapi
    environment:
      - DATABASE_CLIENT=mysql
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=user
      - DATABASE_PASSWORD=userpass
      - DATABASE_AUTHENTICATION_DATABASE=strapi
      - STRAPI_VERSION=latest
    ports:
      - 1337:1337
    volumes:
      - ./backend:/srv/app
    depends_on:
      - mysql
  frontend:
    image: node:lts
    # image: crowdcode/gridsome-cli
    ports:
      - 8080:8080
    working_dir: /app
    # user: root
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start
    # command: npm i && npm start
    depends_on:
      - strapi

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    # restart: always
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: 4Dm1n!
      MYSQL_DATABASE: strapi
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - 3309:3306
    volumes:
      - ./db_mysql:/var/lib/mysql
      - /my-config:/etc/mysql/conf.d

  # mongo:
  #   container_name: mongo
  #   image: mongo
  #   environment:
  #     - MONGO_INITDB_DATABASE=strapi
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - ./db:/data/db
  #   # restart: always

  # postgres:
  #   image: postgres
  #   ports:
  #       - 5432:5432
  #   volumes:
  #       - ./db_data:/var/lib/postgresql/data
  #   environment:
  #       POSTGRES_PASSWORD: 4Dm1n!
  #       POSTGRES_USER: strapi
  #       POSTGRES_DB: strapi
